project:
  type: book

lang: pt

book:
  title: "Probabilidade e Inferência Estatística para Ciência de Dados"
  author: "Magno T. F. Severino"
  date: "today"
  
  chapters:
    - index.qmd
    
    - part: 010_probabilidade.qmd
      chapters:
        - aula01.qmd
        - aula02.qmd
        - aula03.qmd
        - aula04.qmd
        - aula05.qmd
        - aula06.qmd
        - aula07.qmd
        - aula08.qmd
        - aula09.qmd
        - aula10.qmd
        - aula11.qmd
        - aula12.qmd
    
    - part: 020_inferencia.qmd
      chapters:
        - aula24.qmd
        
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: true

crossref:
  chapters: true
  fig-prefix: "Figura"
  tbl-prefix: "Tabela"
  eq-prefix: "Eq."
  def-prefix: "Definição"
  exm-prefix: "Exemplo"
  prp-prefix: "Proposição"
  thm-prefix: "Teorema"


