on:
  push:
    branches:
      - main

name: Renderizar e Publicar Livro Quarto

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - name: Cache R Packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          # CORREÇÃO: Aponta para este arquivo para a chave do cache
          key: ${{ runner.os }}-r-${{ hashFiles('.github/workflows/publish.yml') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R Packages
        run: |
          # CORREÇÃO: 'knitr' e lista de pacotes otimizada
          R -e "install.packages(c('rmarkdown', 'knitr', 'tidyverse', 'kableExtra'))"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Book
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _book