on:
  push:
    branches:
      - main

name: Renderizar e Publicar Livro Quarto

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Book
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Publish to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target-branch: gh-pages
          dir: _book