on:
  push:
    branches:
      - main

name: Renderizar e Publicar Livro Quarto

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R and Install Packages
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'
          
          # 1. Diz à ação para usar o cache
          use-r-cache: true 
          
          # 2. Lista os pacotes para instalar
          packages: |
              rmarkdown
              knitr
              tidyverse
              kableExtra
            
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Book
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _book